name: memote

on:
  push:
    branches:
    - main
    - devel
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:
    inputs:
      py-act:
        description: 'Python 3.X for GH Actions'
        required: TRUE
        default: '3.8'
      pip_opts:
        description: Install options (pip)
        required: false
        default: '--upgrade'
env:
  ACTIONS_SETUP_PY3: ${{ github.event.inputs.py-act }}
  PIP_INSTALL_OPTS: ${{ github.event.inputs.pip_opts }}

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Set up Python ${{ env.ACTIONS_SETUP_PY3 }}
      id: setup
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.ACTIONS_SETUP_PY3 }}
    -
      name: Set Python ${{ env.ACTIONS_SETUP_PY3 }} cache
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-pydeps-${{ env.pythonLocation }}-${{ hashFiles('setup.cfg') }}-${{ hashFiles('pyproject.toml') }}
    -
      name: Install dependencies
      run: |
        python -m pip install ${{ env.PIP_INSTALL_OPTS }} pip
        python -m pip install ${{ env.PIP_INSTALL_OPTS }} memote~=0.13.0
    -
      name: Run memote on deployment branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HEAD_REF: ${{ github.ref_name }}
      run: ./scripts/ghactions_deploy.sh
